pczbudget/src/main/java/polcz/budget/session/TransactionBean.java
package polcz.budget.session;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.AjaxBehaviorEvent;

import org.junit.Assert;
import org.primefaces.component.datatable.DataTable;
import org.primefaces.event.RowEditEvent;

import polcz.budget.global.R;
import polcz.budget.model.TChargeAccount;
import polcz.budget.model.TCluster;
import polcz.budget.model.TMarket;
import polcz.budget.model.TTransaction;
import polcz.budget.model.TTransactionType;
import polcz.budget.service.AbstractService;
import polcz.budget.service.CAService;
import polcz.budget.service.ClusterService;
import polcz.budget.service.MarketService;
import polcz.budget.service.StartupService;
import polcz.budget.service.TransactionService;
import polcz.budget.service.helper.TransactionArguments;
import polcz.budget.session.helper.AbstractEntityBean;

/**
 * Ez borzasztoan bonyolultra sikerult, atgondolast igenyel
 */
@ManagedBean
@SessionScoped
public class TransactionBean extends AbstractEntityBean<TTransaction> implements Serializable
{

    private static final long serialVersionUID = -8931274643248777827L;
    // @Getter
    private final int ID = new Random(System.currentTimeMillis()).nextInt();

    /// @formatter:off
    @EJB private StartupService ss;
    @EJB private TransactionService trservice;
    @EJB private CAService caservice;
    @EJB private MarketService mkservice;
    @EJB private ClusterService clservice;
    /// @formatter:on

    // @ManagedProperty(value = "#{mecBean}")
    // private MapEntityConverter mecBean;

    /* edit or create actual transaction entry */
    private Date date;
    private TChargeAccount ca;
    private TChargeAccount catransfer;
    private int amount;
    private int balance;
    private TCluster cluster;
    private TMarket market;
    private String remark;
    private boolean pivot;
    // private String remarkExtra;
    // private Integer balanceTmp;

    /* type of modification: insertion, update or removal */
    private TTransactionType type;

    /* the older transaction, which is going to be updated [type == update] */
    private TTransaction old;

    /* filter parameters */
    private TChargeAccount filterCa;
    private TChargeAccount filterCatransfer;
    private TCluster filterCluster;
    private TMarket filterMarket;

    public TransactionBean()
    {
        super(TransactionBean.class);
    }

    @PostConstruct
    public void init()
    {
        super.init();
        // filterCa = ss.pkez();
        Assert.assertNotNull(ss.CA_None());
    }

    public TTransactionType[] getTypes()
    {
        return TTransactionType.values();
    }

    public String create()
    {
        date = new Date(); /* today */
        amount = 0;
        balance = 0;
        ca = ss.pkez();
        cluster = ss.Napi_Szukseglet();
        market = ss.Market_Not_Applicable();
        remark = null;
        pivot = false;
        catransfer = ss.CA_None();
        type = TTransactionType.simple;

        log(String.format("trDate = %s", new SimpleDateFormat("yyyy-MM-dd").format(date)));
        return R.REDIRECT_CREATE;
    }

    public String edit(TTransaction tr)
    {
        log("edit transaction: %s", tr);

        uid = tr.getUid();
        date = tr.getDate();
        amount = tr.getAmount();
        balance = tr.getBalance();
        remark = tr.getRemark();
        pivot = tr.isPivot();
        ca = tr.getCa();
        catransfer = tr.getCatransfer();
        cluster = tr.getCluster();
        market = tr.getMarket();

        Assert.assertNotNull("ca is null", ca);
        Assert.assertNotNull("catransfer is null", catransfer);
        Assert.assertNotNull("market is null", market);
        Assert.assertNotNull("cluster is null", cluster);

        if (pivot)
        {
            Assert.assertTrue(String.format("in pivot case, the catransfer should be 'none'. "
                + "Expected: %s, got %s", ss.CA_None(), catransfer),
                ss.CA_None().equals(catransfer));

            type = TTransactionType.pivot;
        }
        else if (catransfer.equals(ss.CA_None()))
        {
            type = TTransactionType.simple;
        }
        else
        {
            type = TTransactionType.transfer;
        }

        /* here I store the old values of the selected transaction item */
        // TODO: tr.clone()
        old = new TTransaction();
        old.setCa(ca);
        old.setCatransfer(catransfer);
        old.setDate(date);

        log(String.format("amount = %d, balance = %d, cluster = %s, market = %s, ca = %s, catrans = %s",
            amount,
            balance, cluster.getName(), market.getName(), ca.getName(), catransfer.getName()));

        return R.REDIRECT_EDIT;
    }

    public String updateView()
    {
        updateList();
        return R.REDIRECT_VIEW;
    }

    @Override
    public List<TTransaction> updateList()
    {
        // TODO: egy ido utan ez egy kicsit lassu lesz (ha sok sora lesz)
        list = trservice.findAll(filterCa, filterCatransfer, filterCluster, filterMarket);
        log(this.getClass().getSimpleName() + "::updateList(), length = " + list.size());
        log(String.format("ca = %s, mk = %s, cl = %s", filterCa, filterMarket, filterCluster));
        return list;
    }

    /**
     * Supply additional (necessary) data to the transaction instance, which are
     * not given by the UI.
     */
    private TTransaction validate(TTransaction tr)
    {
        /* this is processed after the JSF validation was done */

        log("TRANSACTION TYPE: " + type.getName());

        if (type == TTransactionType.pivot)
        {
            tr.setPivot(true);
            tr.setAmount(0);
            tr.setCluster(ss.Szamolas());
            tr.setMarket(ss.Market_Not_Applicable());
            tr.setCatransfer(ss.CA_None());
        }
        else if (type == TTransactionType.transfer)
        {
            tr.setPivot(false);
            tr.setBalance(0);
            tr.setCluster(ss.Athelyezes());
            tr.setMarket(ss.Market_Not_Applicable());

            Assert.assertFalse("In transfer mode the catransfer shouldn't be 'none'",
                tr.getCatransfer().equals(ss.CA_None()));
        }
        else if (type == TTransactionType.simple)
        {
            tr.setPivot(false);
            tr.setBalance(0);
            tr.setCatransfer(ss.CA_None());
        }

        Assert.assertNotNull(tr.getCa());
        Assert.assertNotNull(tr.getCatransfer());

        return tr;
    }

    @Override
    public String persist()
    {
        TTransaction newtr = validate(instance());
        log("persist: %s ", newtr);

        trservice.makeTransaction(new TransactionArguments(newtr, null, R.TR_INSERTION));
        return updateView();
    }

    @Override
    public String merge()
    {
        TTransaction tr = validate(instance(uid));

        log("WILL BE UPDATED: %s", tr);

        trservice.makeTransaction(new TransactionArguments(tr, old, R.TR_UPDATE));
        return updateView();
    }

    @Override
    public String remove(TTransaction removable)
    {
        log("WILL BE REMOVED: %s", removable);

        TTransaction tr = trservice.findFirstSimpleTransactionBefore(removable);
        log("FIRST SIMPLE TRANSACTION BEFORE THE REMOVABLE: %s", tr);

        trservice.makeTransaction(new TransactionArguments(tr, removable, R.TR_REMOVAL));
        return updateView();
    }

    @Override
    public TTransaction instance()
    {
        return new TTransaction(amount, balance, date, remark, ca, cluster, market, pivot)
            .setCatransfer(catransfer);
    }

    @Override
    public TTransaction instance(int uid)
    {
        return instance().setUid(uid);
    }

    @Override
    public AbstractService<TTransaction> getService()
    {
        return trservice;
    }

    /* ============================ ROW EDIT EVENTS ============================= */

    public void onEdit(RowEditEvent event)
    {
        logger.info("onEdit(RowEditEvent)");

        AjaxBehaviorEvent evt = (AjaxBehaviorEvent) event;
        DataTable table = (DataTable) evt.getSource();
        int activeRow = table.getRowIndex();

        log(list.get(activeRow).getRemark());
        trservice.edit(list.get(activeRow));
    }

    public void onCancel(RowEditEvent event)
    {
        logger.info("onCancel(RowEditEvent)");
    }

    /* ============================ GETTERS / SETTERS ============================= */

    public TTransaction getOld()
    {
        return old;
    }

    public void setOld(TTransaction old)
    {
        this.old = old;
    }

    public Date getDate()
    {
        return date;
    }

    public void setDate(Date date)
    {
        this.date = date;
    }

    public TChargeAccount getCa()
    {
        return ca;
    }

    public void setCa(TChargeAccount ca)
    {
        this.ca = ca;
    }

    public TChargeAccount getCatransfer()
    {
        return catransfer;
    }

    public void setCatransfer(TChargeAccount catransfer)
    {
        this.catransfer = catransfer;
    }

    public int getAmount()
    {
        return amount;
    }

    public void setAmount(int amount)
    {
        this.amount = amount;
    }

    public int getBalance()
    {
        return balance;
    }

    public void setBalance(int balance)
    {
        this.balance = balance;
    }

    public TCluster getCluster()
    {
        return cluster;
    }

    public void setCluster(TCluster cluster)
    {
        this.cluster = cluster;
    }

    public TMarket getMarket()
    {
        return market;
    }

    public void setMarket(TMarket market)
    {
        this.market = market;
    }

    public String getRemark()
    {
        return remark;
    }

pczbudget/src/main/webapp/resources/mycomponents/editClusterComp.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:composite="http://xmlns.jcp.org/jsf/composite"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui" 
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<composite:interface>
	<composite:attribute name="name" required="true" />
	<composite:attribute name="sgn" required="true" />
	<composite:attribute name="parentcl" required="false" />
	<composite:attribute name="desc" required="false" /> <!-- UNUSED -->
</composite:interface>

<composite:implementation>
	<h:messages globalOnly="true" styleClass="error" />

	<h:panelGrid columnClasses="label,component,required" columns="3">


		<h:outputLabel for="name" value="Cluster name:" />
		<h:panelGroup>
			<h:inputText id="name" required="true" value="#{cc.attrs.name}">
				<f:validateRequired />
			</h:inputText>
			<h:message for="name" styleClass="error" />
		</h:panelGroup>
		<h:outputText value="*" />


		<ui:remove>
			<!--                <h:outputLabel for="desc" value="Description:" />
                                <h:panelGroup>
                                    <h:inputText id="desc" required="false" value="#{cc.attrs.desc}">
                                    </h:inputText>
                                    <h:message for="desc" styleClass="error" />
                                </h:panelGroup>
                                <h:outputText value="*" /> -->
		</ui:remove>


		<h:outputLabel for="sgn" value="Direction (+/-)" />
		<h:panelGroup>
            <h:inputText id="sgn" required="true" value="#{cc.attrs.sgn}" type="number" min="-1" max="1"
                step="2">
                <f:validateRequired />
            </h:inputText>
            <h:message for="sgn" styleClass="error" />
		</h:panelGroup>
		<h:outputText value="*" />


		<h:outputLabel for="cl_uid" value="Parent cluster:" />
		<h:panelGroup>
            <p:selectOneMenu id="cl_uid" required="false" value="#{cc.attrs.parentcl}" style="width:320px"
                converter="#{mecBean}">
                <f:selectItems value="#{clBean.items}" />
            </p:selectOneMenu>
            <h:message for="cl_uid" styleClass="error" />
		</h:panelGroup>
		<!-- <h:outputText value="*" /> -->


	</h:panelGrid>
</composite:implementation>
</html>

pczbudget/src/main/webapp/resources/mycomponents/editCustomerComp.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:composite="http://xmlns.jcp.org/jsf/composite"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<composite:interface>
	<composite:attribute name="userName" required="true" />
	<composite:attribute name="lastName" required="true" />
	<composite:attribute name="firstName" required="true" />
	<composite:attribute name="role" required="true" />
	<composite:attribute name="password" required="true" />
</composite:interface>
<composite:implementation>
	<h:messages globalOnly="true" styleClass="error" />

	<h:panelGrid columnClasses="label,component,required" columns="3">
		<h:outputLabel for="userName" value="Felhasználó neve:" />
		<h:panelGroup>
			<h:inputText id="userName" required="true"
				value="#{cc.attrs.userName}">
				<f:validateRequired />
			</h:inputText>
			<h:message for="userName" styleClass="error" />
		</h:panelGroup>
		<h:outputText value="*" />
		<h:outputLabel for="lastName" value="Vezetéknév:" />
		<h:panelGroup>
			<h:inputText id="lastName" required="true"
				value="#{cc.attrs.lastName}" />
			<h:message for="lastName" styleClass="error" />
		</h:panelGroup>
		<h:outputText value="*" />
		<h:outputLabel for="firstName" value="Keresztnév:" />
		<h:panelGroup>
			<h:inputText id="firstName" required="true"
				value="#{cc.attrs.firstName}" />
			<h:message for="firstName" styleClass="error" />
		</h:panelGroup>
		<h:outputText value="*" />
		<h:outputLabel for="role" value="Szerepkör:" />
		<h:panelGroup>
			<h:selectOneMenu id="role" required="true" value="#{cc.attrs.role}">
				<f:selectItem itemValue="ADMIN" itemLabel="ADMIN" />
				<f:selectItem itemValue="GUEST" itemLabel="GUEST" />
				<f:selectItem itemValue="CUSTOMER" itemLabel="CUSTOMER" />
			</h:selectOneMenu>
			<h:message for="role" styleClass="error" />
		</h:panelGroup>
		<h:outputText value="*" />
		<h:outputLabel for="password" value="Jelszó:" />
		<h:panelGroup>
			<h:inputSecret id="password" required="true"
				value="#{cc.attrs.password}">
				<f:validateRequired />
				<f:validator validatorId="passwordValidator" />
			</h:inputSecret>
			<h:message for="password" styleClass="error" />
		</h:panelGroup>
		<h:outputText value="*" />
	</h:panelGrid>
</composite:implementation>
</html>

pczbudget/src/main/webapp/resources/mycomponents/editNameDescComp.xhtml
<!DOCTYPE html
  PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN'
  'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:composite="http://xmlns.jcp.org/jsf/composite"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<composite:interface>
	<composite:attribute name="name" required="true" />
	<composite:attribute name="desc" required="false" />
</composite:interface>
<composite:implementation>
	<h:messages globalOnly="true" styleClass="error" />
	<h:panelGrid columnClasses="label,component,required" columns="3">

        <h:outputLabel for="name" value="Name:" />
        <h:panelGroup>
            <h:inputText id="name" required="true" value="#{cc.attrs.name}">
                <f:validateRequired />
            </h:inputText>
            <h:message for="name" styleClass="error" />
        </h:panelGroup>
        <h:outputText value="*" />

		<h:outputLabel for="desc" value="Description:" />
		<h:panelGroup>
			<h:inputText id="desc" required="false" value="#{cc.attrs.desc}" />
			<h:message for="desc" styleClass="error" />
		</h:panelGroup>
		<!-- <h:outputText value="*" /> -->

	</h:panelGrid>
</composite:implementation>
</html>

pczbudget/src/main/webapp/resources/mycomponents/editTransactionComp.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:composite="http://xmlns.jcp.org/jsf/composite"
    xmlns:of="http://omnifaces.org/functions" xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:t="http://myfaces.apache.org/tomahawk"
    xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">

<composite:interface>
    <composite:attribute name="date" required="true" />
    <composite:attribute name="amount" required="true" />
    <composite:attribute name="balance" required="true" />
    <composite:attribute name="ca_uid" required="true" />
    <composite:attribute name="catransfer_uid" required="true" />
    <composite:attribute name="cl_uid" required="true" />
    <composite:attribute name="mk_uid" required="true" />
    <composite:attribute name="remark" required="false" />
    <composite:attribute name="remark_extra" required="false" />
    <composite:attribute name="pivot" required="true" />
    <!-- TODO: ez elvileg nem kell ide -->
    <composite:attribute name="type" required="true" />
</composite:interface>

<composite:implementation>
    <h:messages globalOnly="true" styleClass="error" />
    <p:messages id="global_msg" globalOnly="true" showDetail="true" autoUpdate="true" closable="true" />

    <p:message for="date" styleClass="error" />
    <p:calendar id="date" mode="inline" pages="4" value="#{cc.attrs.date}" />

    <p:messages id="globalMessage" closeable="true" styleClass="error" />

    <h:panelGrid columnClasses="label,component" columns="2">



        <h:outputLabel for="amount" value="Amount:" />
        <h:panelGroup>
            <p:inputText id="amount" required="true" value="#{cc.attrs.amount}" style="width:320px">
                <f:validateRequired />
            </p:inputText>
            <br />
            <p:message for="amount" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="balance" value="Balance:" />
        <h:panelGroup>
            <p:inputText id="balance" required="true" value="#{cc.attrs.balance}" style="width:320px">
                <f:validateRequired />
            </p:inputText>
            <br />
            <p:message for="balance" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="ca_uid" value="Charge account:" />
        <h:panelGroup>
            <p:selectOneMenu id="ca_uid" value="#{cc.attrs.ca_uid}" required="true" style="width:320px"
                validator="#{trValidator.validateChargeAccountFrom}" converter="#{mecBean}">
                <f:selectItems value="#{caBean.items}" widgetVar="caWidget" />
            </p:selectOneMenu>
            <br />
            <p:message for="ca_uid" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="cl_uid" value="Name of cluster:" />
        <h:panelGroup>
            <p:selectOneMenu id="cl_uid" value="#{cc.attrs.cl_uid}" required="false" style="width:320px"
                validator="#{trValidator.validateCluster}" converter="#{mecBean}" widgetVar="clusterWidget">
                <f:selectItems value="#{clBean.items}" />
            </p:selectOneMenu>
            <br />
            <p:message for="cl_uid" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="mk_uid" value="Market:" />
        <h:panelGroup>
            <p:selectOneMenu id="mk_uid" value="#{cc.attrs.mk_uid}" required="false" style="width:320px"
                validator="#{trValidator.validateMarket}" converter="#{mecBean}" widgetVar="marketWidget">
                <f:selectItems value="#{mkBean.items}" />
            </p:selectOneMenu>
            <br />
            <p:message for="mk_uid" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="remark" value="Remark:" />
        <h:panelGroup>
            <h:inputText id="remark" required="false" value="#{cc.attrs.remark}">
                <!-- <f:validateRequired /> -->
            </h:inputText>
            <br />
            <p:message for="remark" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="remark_extra" value="Extra remark:" />
        <h:panelGroup>
            <h:inputText id="remark_extra" required="false" value="Not implemented yet" readonly="true">
            </h:inputText>
            <br />
            <p:message for="remark_extra" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="ca_transfer_uid" value="Beneficiary charge account:" />
        <h:panelGroup>
            <p:selectOneMenu id="ca_transfer_uid" required="false" style="width:320px"
                value="#{cc.attrs.catransfer_uid}" validator="#{trValidator.validateChargeAccountTo}"
                converter="#{mecBean}" widgetVar="catransferWidget">
                <f:selectItems value="#{caBean.items}" />
            </p:selectOneMenu>
            <br />
            <p:message for="ca_transfer_uid" styleClass="error" />
        </h:panelGroup>



        <h:outputLabel for="type" value="Transacion type:" />
        <h:panelGroup>
            <p:selectOneButton id="type" value="#{cc.attrs.type}">
                <f:selectItems value="#{transactionBean.types}" />
                <ui:remove>
                    <f:selectItem itemLabel="simple" itemValue="simple" />
                    <f:selectItem itemLabel="pivot" itemValue="pivot" />
                    <f:selectItem itemLabel="transfer" itemValue="transfer" />
                </ui:remove>
            </p:selectOneButton>
        </h:panelGroup>




        <script>
	    $(document).ready(function() {
	        var amount = document.getElementById('search:component:amount');
	        var balance = document.getElementById('search:component:balance');

	        var type = "";
	        var selected = $('input[type=radio][name=search\\:component\\:type]:checked');
	        if (selected.length > 0) {
	            type = selected.val();
	        }

	        function enableDisable(value) {
	            if (value == 'simple')
	            {
	                amount.readOnly = false;
	                balance.readOnly = true;
                    PF('catransferWidget').disable();
                    PF('marketWidget').enable();
                    PF('clusterWidget').enable();
	            }
	            else if (value == 'pivot')
	            {
	                amount.readOnly = true;
	                balance.readOnly = false;
                    PF('catransferWidget').disable();
                    PF('marketWidget').disable();
                    PF('clusterWidget').disable();
	            }
	            else if (value == 'transfer')
	            {
	                amount.readOnly = false;
	                balance.readOnly = true;
                    PF('catransferWidget').enable();
                    PF('marketWidget').disable();
                    PF('clusterWidget').disable();
	            }

	            if (amount.readOnly) amount.value = 0;
	            if (balance.readOnly) balance.value = 0;
	        }
	        enableDisable(type);

	        $('input[type=radio][name=search\\:component\\:type]').change(function() {
	            enableDisable(this.value);
	        });
	    });
		
        // $( "p" ).append( "<strong>Hello</strong>" );
        
        // $('#search\\:component\\:ispivot_input').change(function() {
        //     // javascript-ben nem vagyon nagy szaki
        //     var amount = document.getElementById('search:component:amount');
        //     var balance = document.getElementById('search:component:balance');
        //     // --
        //     amount.readOnly = this.checked;
        //     amount.required = !this.checked;
        //     // --
        //     balance.readOnly = !this.checked;
        //     balance.required = this.checked;
        //     $('#search\\:component\\:cl_uid').attr('disabled', this.checked);
        //     $('#search\\:component\\:mk_uid').attr('disabled', this.checked);
        //     if (this.checked) $('#search\\:component\\:transfer').attr('value', false);
        // });
        
		</script>

    </h:panelGrid>


    <ui:remove>
        <h:outputText value="Selected:" />
        <h:outputText id="display" value="#{selectOneView.option}" style="font-weight: bold" />

        <p>I would like to say:</p>

        <h:outputLabel for="ispivot" value="Is pivot:" />
        <h:panelGroup>
            <p:selectBooleanButton id="ispivot" value="#{cc.attrs.ispivot}" onLabel="Yes" offLabel="No"
                style="width:60px" />
            <h:message for="ispivot" styleClass="error" />
        </h:panelGroup>

        <h:outputLabel for="transfer" value="Transfer:" />
        <h:panelGroup>
            <p:selectBooleanButton id="transfer" value="#{cc.attrs.transfer}" onLabel="Yes" offLabel="No"
                style="width:60px" />
            <h:message for="transfer" styleClass="error" />
        </h:panelGroup>

        <p>I would like to say:</p>
        <script>
        // document.getElementById('search:component:pivot_input').onchange = function() {
        //     $( "p" ).append( "<strong>Hello</strong>" );
        // };
        </script>
    </ui:remove>

</composite:implementation>
</html>